---
title: "Untitled"
author: "fio"
date: "2025-10-02"
output: html_document
Cabecera:
output: 
  github_document: default
  html_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_format = "all") })
editor_options: 
  markdown: 
    wrap: 72
---

```{r}
data_path<- file.path("C:/Users/Family2/Documents/4SEMESTRE/Estadistica_IV/UNIDAD_1")
data_file<- file.path(data_path, "vgsales.csv")
data.vg.raw<- read.csv(data_file, 
                       stringsAsFactors = F, na.strings = ".", header = T, sep = ",")
head(data.vg.raw)
str(data.vg.raw)
summary(data.vg.raw)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

## Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
data.vg.raw$Year<- as.integer(data.vg.raw$Year)
summary(data.vg.raw)
data.vg.raw$Genre<- as.factor(data.vg.raw$Genre)
summary(data.vg.raw)
```

```{r}
unique(data.vg.raw$Name)
```

```{r}
length(unique(data.vg.raw$Name))
```

```{r}
filter(data.vg.raw,Name=="FIFA 15")
```
